/*
 * Description : Blinking Led "Hello World" project.
 * Code initializes PORTB PIN0 as output pin and toggles 
 * the LED with 1000ms delay.
 * Delay is generated by the inbuilt API.
 * __delay_ms(int in milli seconds).
 * 
 * 
 */
#include <xc.h>
/*========================================================*&*CONFIGURATION BITS*&*========================================================*/

#pragma config FOSC = HS        // Oscillator Selection bits (HS oscillator)
#pragma config WDTE = OFF       // Watchdog Timer Enable bit (WDT disabled)
#pragma config PWRTE = OFF      // Power-up Timer Enable bit (PWRT disabled)
#pragma config BOREN = ON       // Brown-out Reset Enable bit (BOR enabled)
#pragma config LVP = OFF        // Low-Voltage (Single-Supply) In-Circuit Serial Programming Enable bit (RB3 is digital I/O, HV on MCLR must be used for programming)
#pragma config CPD = OFF        // Data EEPROM Memory Code Protection bit (Data EEPROM code protection off)
#pragma config WRT = OFF        // Flash Program Memory Write Enable bits (Write protection off; all program memory may be written to by EECON control)
#pragma config CP = OFF         // Flash Program Memory Code Protection bit (Code protection off)

/*========================================================*&*MACRO DEFINITION*&*========================================================*/

#define _XTAL_FREQ 20000000 //defining OSC FREQ for delay routine.
/* User defined Macros */
#define TRUE 1
#define LED RB0
#define ON 1
#define OFF 0

/*========================================================*&*USER FUNCTION*&*========================================================*/

void main(void) {
    
    /* Initialize PORTB->PIN->0->(RB0) to 0(CLEARING THE OUTPUT)*/
    LED = 0;   
    /* Configure RB0 as OUTPUT PIN */
    TRISB0 = 0;
    
    /* Infinite Loop function */
    /* This type of software architecture is called Simple Control Loop */
    while(TRUE){
        /* Turn LED ON */
        LED = ON;
        /* Generate delay of 1sec */
        __delay_ms( 1000 );
        /* Turn LED OFF */
        LED = OFF;
        __delay_ms( 1000 ); 
    }
    
    return;
}

/*========================================================*&*END*&*========================================================*/
